### ISSUE TITLE
scalar production of vec2d gives error

### ISSUE THREAD

**Issue by ekare** [kivy/cymunk#39]
`>>> a=pm.Vec2d(1,1)

> > > a
> > > <cymunk.Vec2d x=1.000000 y=1.000000>
> > > a.normalized
> > > <built-in method normalized of cymunk.cymunk.Vec2d object at 0x7f11d6cfd090>
> > > a.normalized()
> > > <cymunk.Vec2d x=0.707107 y=0.707107>
> > > 40*a.normalized()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "cymunk/core.pxi", line 256, in cymunk.cymunk.Vec2d.**mul** (cymunk/cymunk.c:14152)
> > > TypeError: 'int' object has no attribute '**getitem**'
> > > `

**Comment by SleepProgger** [comment]
The reason of this behavior is that the Vec2d class uses pythons magic function (`__mul__`...) format but cython magic functions behave differently.
See http://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#arithmetic-methods.

There are no "right side of operation" functions (rmul, rsub,...) like in python. but the same arithmetic function is called for the right side with `self` set to the left value and `other` to the right if the magic function of the left side returns `NotImplemented`

A fix for the `__mul__` function could look like this:
```
    def __imul__(self, other):
        if isinstance(other, Vec2d):
            self.x *= other.x
            self.y *= other.y
        elif (hasattr(other, "__getitem__")):
            self.x *= other[0]
            self.y *= other[1]
        else:
            self.x *= other
            self.y *= other
        return self

```

I could prepare a PR with "cythonized" magic functions some when the next days.
