### ISSUE TITLE
Cymunk License

### ISSUE THREAD

**Issue by jupart** [kivy/cymunk#44]
Most (if not all) Kivy projects I've seen use an MIT license, but I'm having trouble finding a license file here. Is this true for Cymunk as well?

**Comment by SleepProgger** [comment]
+1 for license.
Chipmunk also uses the MIT license.

ATM the usage of this module in commercial applications might be problematic, no ?

**Comment by jupart** [comment]
Absolutely. Currently no one has any license to use this code in any way.
